export const SEARCHING = 'SEARCHING';
export const SEARCH_INPUT = 'SEARCH_INPUT';
export const GET_SEARCH_RESULTS = 'GET_SEARCH_RESULTS';
export const REMOVE_SEARCH_RESULTS = 'REMOVE_SEARCH_RESULTS';
export const UPDATE_SEARCH_HISTORY = 'UPDATE_SEARCH_HISTORY';
export const CLEAR_HISTORY = 'CLEAR_HISTORY';
export const IS_FOCUSED = 'IS_FOCUSED';
export const GET_PLACES = 'GET_PLACES';