export const GET_SEARCH_TERM = 'GET_SEARCH_TERM';
export const REMOVE_SEARCH_TERM = 'REMOVE_SEARCH_TERM';
export const SEARCHING = 'SEARCHING';
export const GET_SEARCH_RESULTS = 'GET_SEARCH_RESULTS';
export const REMOVE_SEARCH_RESULTS = 'REMOVE_SEARCH_RESULTS';